Feature/depot pallet buildups
NoSoft-SA/nspack pull request #163
Opened 2021-11-17 09:30 UTC by lmatoti

Summary of this change:
Depot Pallet Buildups

2021-11-17 14:09 UTC, jcsjcs requested changes

2021-11-18 09:42 UTC, lmatoti commented on lib/messcada/validations/sequences_match_schema.rb
> +  SequencesMatchSchema = Dry::Schema.Params do # rubocop:disable Metrics/BlockLength
it's used in lib/messcada/repositories/messcada_repo.rb
def matching_sequence(pallet_id, sequence_id)

2021-11-18 09:42 UTC, lmatoti commented
Depot Pallet Buildups
Code review hanges implemented

2021-11-18 19:16 UTC, jcsjcs requested changes

2021-11-18 19:16 UTC, jcsjcs commented on lib/finished_goods/repositories/buildups_repo.rb
> +    end
This query is still selecting from `vw_pallet_sequence_flat`. Non-report queries should almost never use views.because they are difficult to make efficient. Write a proper query or use `MesscadaApp::DatasetPalletSequence`.

2021-11-22 07:55 UTC, lmatoti commented
Depot Pallet Buildups
Uses MesscadaApp::DatasetPalletSequence instead of view

2021-11-23 09:06 UTC, merged