Feature/presorting
NoSoft-SA/nspack pull request #24
Opened 2021-07-29 11:41 UTC by lmatoti

Summary of this change:

Presorting

Staging runs, for presort plants, allows a user to set up the definition (set of attributes) for which bins should be staged in preparation for a presort run in a presort plant

CHANGELOG entry:
Added

    .New presort staging application

Changed

Fixed

    .

How to test this code via the UI:
Raw Materials | Presorting | (Search/List) Staging Runs

    (Search/List) Staging Runs -> New Presort Staging Run: Fill in and create a new presort_staging_run in editing state.
    Complete Setup :
    Edit Presort Staging Run(grid action): Here you can edit presort_staging_run. You can also add children to the run.
    New Staging Run Child: Select a farm and create a new presort_staging_run_child in editing state
    Activate Run(presort_staging_run_children grid action): Activates a child_run. Only one child_run can be active at a time.
    Complete Run(presort_staging_run_children grid action):Completes the actve child_run.
    Back to Menu (Search/List) Staging Runs -> Complete Setup(grid action): This completes the setup.
    Uncomplete Setup(grid action): This reverses complete_setup i.e. uncompletes the setup.
    Activate Run(grid action): Instead of uncompleting you can activate the run instead. NB. Only one active run per presort plant can be active at a time.
    Complete Sstagin(grid action):Completes the staging process for this run i.e. allows to be able to go and active another run.

2021-08-03 10:21 UTC, lmatoti commented
Summary of this change:

Presorting

Staging runs, for presort plants, allows a user to set up the definition (set of attributes) for which bins should be staged in preparation for a presort run in a presort plant

CHANGELOG entry:
Added

Changed
Presorting now uses process step to manage a run's states

Fixed

.

How to test this code via the UI:
Raw Materials | Presorting | (Search/List) Staging Runs

(Search/List) Staging Runs -> New Presort Staging Run: Fill in and create a new presort_staging_run in editing state.
Manage (presort_staging_run grid action): Here you can manage presort_staging_run and it's children.
New Staging Run Child: Select a farm and create a new presort_staging_run_child in editing state
Activate Run(presort_staging_run_children grid action): Activates a child_run. Only one child_run can be active at a time.
Complete Run(presort_staging_run_children grid action):Completes the actve child_run.

Buttons
Complete Setup: This completes the setup.
Uncomplete Setup: This reverses complete_setup i.e. uncompletes the setup.
Activate Run: Instead of uncompleting you can activate the run instead. NB. Only one active run per presort plant can be active at a time.
Complete Sstagin:Completes the staging process for this run i.e. allows to be able to go and active another run.

2021-08-03 13:12 UTC, jcsjcs requested changes
Hi Lux

Please take a look at the code comments.
We'll also need to set up some more resource config so the presort resource can be added to the plant resource tree.

2021-08-03 13:12 UTC, jcsjcs commented on lib/raw_materials/views/presort_staging_run/edit.rb
> +                if rules[:is_kr]
Same as above, use a client rule instead of checking the client code.

2021-08-04 12:15 UTC, lmatoti commented
Implemented changes as per code review

2021-08-05 07:22 UTC, jcsjcs commented on lib/raw_materials/ui_rules/presort_staging_run_rule.rb
> +    end
You could move this method to the client rule itself, then it can be called from anywhere:
```ruby
AppConst::CR_RMT.implements_presort_legacy_data_fields?
```

2021-08-05 08:30 UTC, lmatoti commented
implements_presort_legacy_data_fields? moved to client_rules

2021-08-05 09:38 UTC, merged