Feature/force bin staging
NoSoft-SA/nspack pull request #293
Opened 2022-03-10 12:09 UTC by lmatoti

Summary of this change:
Web app to stage a bin against a selected run(wether run is acive or not)

CHANGELOG entry:

### Added
- New force staging application

How to test this code via the UI:
Raw Materials | Presorting | Force Bin Staging
- Enter bin
- Select a run/child to stage against

2022-03-10 14:15 UTC, jcsjcs requested changes

2022-03-10 14:15 UTC, jcsjcs commented on lib/messcada/services/force_bin_staging.rb
> +      err = bin_from_ra7?(asset_number)
Change this and the valid location check below to use new client rules:
```ruby
presort_bin_staging_locations: { valid_source_location: %w[RA_6 RA_7 PRESORT], invalid_source_location: %w[RA7] }
# then define two methods to call that return the array of location codes or an empty array:
# valid_presort_bin_staging_locations
# invalid_presort_bin_staging_locations
```

2022-03-10 14:15 UTC, jcsjcs commented on lib/messcada/services/force_bin_staging.rb
> +      errs << "bin location_code[#{bin.location_long_code}] is not in [RA_6 or RA_7 or PRESORT]" unless valid_bin_location_for_staging?(asset_number)
Use the `valid_presort_bin_staging_locations` client rule method to resolve the locations without hard-coding.

2022-03-11 08:00 UTC, lmatoti commented on lib/messcada/services/force_bin_staging.rb
> +        StageBins.call([bin_number], plant_resource_code, presort_staging_run_child_id)
StageBins doesn't return anything. However errors are raised inside StageBins

2022-03-11 16:18 UTC, merged