FG Orders: added order value attrs
NoSoft-SA/nspack pull request #307
Opened 2022-03-21 14:02 UTC by ViljoenFritz

CHANGELOG entry:

### Added
- Order value (carton price)
- Order value (Kg price)
- Order item customer price history
### Changed
- set price per kg and price per carton always visible
### Fixed
- order item price history now filters even if values where null

How to test this code via the UI:
look at orders >> order items

2022-03-22 20:19 UTC, ViljoenFritz commented on lib/finished_goods/interactors/order_interactor.rb
> +            mk.col(column.name, column.caption, { width: column.width, data_type: column.data_type, editable: true, cellEditor: 'numericCellEditor' })
can we cast this cell editor as currency

2022-03-22 20:20 UTC, ViljoenFritz commented on lib/finished_goods/entities/order.rb
> +    attribute :order_total_price_per_kg, Types::Decimal
can these types be changed to a currency attribute

2022-03-22 20:21 UTC, ViljoenFritz commented on lib/finished_goods/ui_rules/order_rule.rb
> +                                                with_value: UtilityFunctions.delimited_number(@form_object.order_total_price_per_carton) }
I dont like using the util_func here would rather have the dry struct handle it

2022-03-23 04:54 UTC, jcsjcs requested changes

2022-03-23 04:54 UTC, jcsjcs commented on lib/finished_goods/interactors/order_interactor.rb
> +            mk.col(column.name, column.caption, { width: column.width, data_type: column.data_type, editable: true, cellEditor: 'numericCellEditor' })
There is no currency editor. The grid would also need a column for the currency symbol.

2022-03-23 04:54 UTC, jcsjcs commented on lib/finished_goods/repositories/order_repo.rb
> +      hash[:weight_price_total] = select_values(:pallet_sequences, :nett_weight, order_item_id: id).sum * hash[:price_per_kg].to_f
Using floats is not very accurate - it might be better to use `BigDecimal` to get consistent results.
```ruby
 * (hash[:price_per_carton] || AppConst::BIG_ZERO)
```

2022-03-23 04:54 UTC, jcsjcs commented on lib/finished_goods/validations/order_schema.rb
> +      key.failure('must be filled') if values[:price_per_carton].nil_or_empty? && !BaseRepo.new.get(:orders, :pricing_per_kg, values[:order_id])
Rather pass `price_per_kg` boolean as an option to the Contract.

2022-03-23 05:14 UTC, jcsjcs requested changes

2022-03-23 05:14 UTC, jcsjcs commented on db/migrations/202203222143_alter_order_items_prices.rb
> +  end
What are these view for?

If you create a view in a migration that does not already exist in the db:
* Do not keep the `000000000000` migration file.
* Do not include DROP in the `up` - there is no such view.
* The `down` should just be DROPs
* Change the ALTER to use the ruby migration DSL: `alter_table(:order_items)`...

2022-03-23 05:28 UTC, jcsjcs requested changes

2022-03-23 05:28 UTC, jcsjcs commented on lib/finished_goods/entities/order.rb
> +    attribute :order_total_price_per_kg, Types::Decimal
There is no currency type.

2022-03-23 05:28 UTC, jcsjcs commented on lib/finished_goods/repositories/order_repo.rb
> +      Order.new(hash)
No need for the extra hash copy.
```ruby
Order.new(hash.merge(order_item_value(order_id: id)))
```

2022-03-23 05:28 UTC, jcsjcs commented on lib/finished_goods/repositories/order_repo.rb
>        OrderItem.new(hash)
Don't do the extra hash copy when it is not necessary - include the merge here)

2022-03-23 05:28 UTC, jcsjcs commented on lib/finished_goods/ui_rules/order_rule.rb
> +                                                with_value: UtilityFunctions.delimited_number(@form_object.order_total_price_per_carton) }
Dry struct is not for output formatting.

2022-03-23 14:01 UTC, ViljoenFritz commented on lib/finished_goods/repositories/order_repo.rb
> +      Order.new(hash)
cool

2022-03-23 14:04 UTC, ViljoenFritz commented on lib/finished_goods/interactors/order_interactor.rb
> +            mk.col(column.name, column.caption, { width: column.width, data_type: column.data_type, editable: true, cellEditor: 'numericCellEditor' })
Currently the  coded_grid  columns above does not respect the delimited_1000 setting in order_items.yml

2022-03-24 07:51 UTC, merged