Multiple load allocate
NoSoft-SA/nspack pull request #334
Opened 2022-04-06 20:17 UTC by ViljoenFritz

Summary of this change:

added feature to allocate pallets to multiple loads from text field 

CHANGELOG entry:

### Added
- .Parse load string
- allow loads to be deleted when allocated
### Changed
- rearrange loads ETD->ETA ATA->ATD
- updated factories
### Fixed
- .removed wip pallets check from interactor they are checked in check_pallets

How to test this code via the UI:

loads => manage => allocate => paste list of pallets in text field

2022-04-07 15:05 UTC, jcsjcs requested changes

2022-04-07 17:06 UTC, jcsjcs commented on helpers/utility_functions.rb
> +
Yes, I think tabs will be a valuable addition.

2022-04-07 18:29 UTC, ViljoenFritz commented on helpers/utility_functions.rb
> +
applied changes

2022-04-08 08:35 UTC, jcsjcs requested changes

2022-04-08 08:35 UTC, jcsjcs commented on helpers/utility_functions.rb
>    # Takes a string and returns an array from text split on commas and new lines.
Amend the description to include "tabs".

2022-04-08 08:35 UTC, jcsjcs commented on lib/finished_goods/test/services/test_parse_load_string.rb
>        res = ParseLoadString.call(in_string)
These tests must also pass if there is extra empty space between delimiters:
`"    1  ,  #{pallet_number}  \t   1  \t  #{pallet_number} \n  "`

2022-04-08 10:26 UTC, jcsjcs requested changes

2022-04-08 10:26 UTC, jcsjcs commented on lib/finished_goods/repositories/load_repo.rb
> +      FinishedGoodsApp::Job::CalculateExtendedFgCodesFromSeqs.enqueue(pallet_ids) if AppConst::CR_FG.lookup_extended_fg_code?
Why is the calculation of extended fg called here?

2022-04-08 10:26 UTC, jcsjcs commented on lib/finished_goods/services/parse_load_string.rb
> +      check_non_numeric(output)
Is this necessary if you have called `valid_pallet_number?` already?

2022-04-08 11:26 UTC, ViljoenFritz commented on lib/finished_goods/services/parse_load_string.rb
> +      check_non_numeric(output)
MesscadaApp::ScannedPalletNumber doesnt check for non numeric

2022-04-08 11:26 UTC, ViljoenFritz commented on lib/finished_goods/test/services/test_parse_load_string.rb
>        res = ParseLoadString.call(in_string)
ill add in some spaces

2022-04-08 11:26 UTC, ViljoenFritz commented on lib/finished_goods/repositories/load_repo.rb
> +      FinishedGoodsApp::Job::CalculateExtendedFgCodesFromSeqs.enqueue(pallet_ids) if AppConst::CR_FG.lookup_extended_fg_code?
https://github.com/NoSoft-SA/nspack/pull/334/commits/b2c1454b6caf3521a66b9a360f6c645c87d595d6
it was clogging up the interactor

2022-04-08 11:27 UTC, ViljoenFritz commented on helpers/utility_functions.rb
>    # Takes a string and returns an array from text split on commas and new lines.
done

2022-04-08 11:41 UTC, merged

2022-04-08 11:42 UTC, ViljoenFritz commented on lib/finished_goods/services/parse_load_string.rb
> +      check_non_numeric(output)
ill rename valid_pallet_number to possable_pallet_number