Bugfix scanned number
NoSoft-SA/nspack pull request #361
Opened 2022-04-26 23:21 UTC by ViljoenFritz

Summary of this change:

fixed Unhandled error on MesscadaApp::ScanCartonLabelOrPallet

CHANGELOG entry:

### Added
- [added base repo create to test_helper to inherit prepare_values_for_db](https://github.com/NoSoft-SA/nspack/commit/6b78780b7e72a2876578d3a6feae645307b1fbee)
- [add test_scan_pallet_for_carton_label](https://github.com/NoSoft-SA/nspack/commit/a59d9d61aaf3057d6ac65360f831eca6d145dd11)
### Changed
- [updated factories](https://github.com/NoSoft-SA/nspack/commit/e6cdd3b30b3799ed680847007b826cbb244565c1)
### Fixed
- [fix bug for scan pallet number or scanned number](https://github.com/NoSoft-SA/nspack/commit/8aa3dbf1e013357c252df526e78b41d8afa518eb)

How to test this code via the UI:
 on the "Add Finding Sheet Pallets" RMD app when trying to add a pallet to a gvt inspection sheet.

2022-04-27 06:33 UTC, jcsjcs requested changes

2022-04-27 06:33 UTC, jcsjcs commented on lib/masterfiles/test/factories/fruit_factory.rb
> +      create(:fruit_actual_counts_for_packs, default.merge(opts))
I would rather this was named `db_create`, `create_record`, `repo_create` or something. As a test helper method, `create` is a bit too ambiguous.

2022-04-27 06:33 UTC, jcsjcs commented on lib/messcada/test/factories/carton_factory.rb
> -
Why are you removing the ability to override the foreign keys? What you have removed is the preferred pattern.

2022-04-27 06:33 UTC, jcsjcs commented on test/test_helper.rb
> +  def create(table_name, attrs)
Please rename.

2022-04-27 06:33 UTC, jcsjcs commented on lib/messcada/test/services/test_scan_carton_label_or_pallet.rb
> +      res = MesscadaApp::ScanCartonLabelOrPallet.call(scanned_number)
Is passing a string instead of a hash only valid for scanning a pallet?
Should it also be tested for scanning a carton?

This should also test passing an invalid pallet as a string.

2022-04-27 06:39 UTC, ViljoenFritz commented on lib/masterfiles/test/factories/fruit_factory.rb
> +      create(:fruit_actual_counts_for_packs, default.merge(opts))
ill go with repo_create

2022-04-27 06:40 UTC, ViljoenFritz commented on lib/messcada/test/services/test_scan_carton_label_or_pallet.rb
> +      res = MesscadaApp::ScanCartonLabelOrPallet.call(scanned_number)
ill add the test

2022-04-27 06:43 UTC, ViljoenFritz commented on lib/masterfiles/test/factories/fruit_factory.rb
> +      create(:fruit_actual_counts_for_packs, default.merge(opts))
it reads like repo.create

2022-04-27 06:47 UTC, ViljoenFritz commented on lib/messcada/test/services/test_scan_carton_label_or_pallet.rb
> +      res = MesscadaApp::ScanCartonLabelOrPallet.call(scanned_number)
if an invalid pallet number looks like a carton there would be no way of test that

2022-04-27 17:05 UTC, ViljoenFritz commented on lib/messcada/test/factories/carton_factory.rb
> -
you can still override the foreign keys by passing in the opts **.insert(default.merge(opts))**
I changed it, as with the current scaffold pattern you cant pass in a nil value for any of those ids.

2022-04-27 17:06 UTC, ViljoenFritz commented on test/test_helper.rb
> +  def create(table_name, attrs)
the scaffold should probably change to use this method

2022-04-27 19:14 UTC, jcsjcs commented on lib/messcada/test/factories/carton_factory.rb
> -
No, if the table has an optional foreign key, you write it like this:
```ruby
opts[:palletizer_contract_worker_id] ||= create_contract_worker unless opts.key?(:palletizer_contract_worker_id)
```
That way you retain the ability to override the default with a value or nil, **and** you do not slow the tests down by creating a record in the default before you override it.

2022-04-28 07:05 UTC, ViljoenFritz commented on lib/messcada/test/factories/carton_factory.rb
> -
for the factories shouldn't we rather create records with the minimum values required. 
refactor the scaffold and the factories to remove all the values that are nullable.

 I believe it would make the tests more ridged

2022-05-03 08:42 UTC, jcsjcs requested changes

2022-05-03 08:42 UTC, jcsjcs commented on lib/masterfiles/test/factories/standard_product_weight_factory.rb
Please add:
```ruby
      opts[:commodity_id] ||= create_commodity
      opts[:standard_pack_code_id] ||= create_standard_pack_code
```
and remove below.

2022-05-03 08:42 UTC, jcsjcs commented on lib/messcada/test/factories/carton_factory.rb
> -        tu_sticker_ids: BaseRepo.new.array_for_db_col([]),
Please put the default values back:
```
extended_columns: {},
treatment_ids: [],
fruit_sticker_ids: [],
tu_sticker_ids: [],
```

2022-05-03 08:42 UTC, jcsjcs commented on lib/production/test/factories/product_setup_factory.rb
> -
Please add the opts:
```ruby
      opts[:cultivar_group_id] ||= create_cultivar_group
      opts[:cultivar_id] ||= create_cultivar unless opts.key?(:cultivar_id)
      opts[:plant_resource_id] ||= create_plant_resource unless opts.key?(:plant_resource_id)
      opts[:season_group_id] ||= create_season_group unless opts.key?(:season_group_id)
      opts[:season_id] ||= create_season unless opts.key?(:season_id)
```

2022-05-03 08:42 UTC, jcsjcs commented on lib/production/test/factories/product_setup_factory.rb
> -      product_setup_template_id = create_product_setup_template
Please add the opts:
```ruby
      opts[:product_setup_template_id] ||= create_product_setup_template
      opts[:marketing_variety_id] ||= create_marketing_variety
      opts[:customer_variety_id] ||= create_customer_variety unless opts.key?(:customer_variety_id)
      opts[:basic_pack_code_id] ||= create_basic_pack_code
      opts[:standard_pack_code_id] ||= create_standard_pack_code
      opts[:fruit_actual_counts_for_pack_id] ||= create_fruit_actual_counts_for_pack unless opts.key?(:fruit_actual_counts_for_pack_id)
      opts[:mark_id] ||= create_mark
      opts[:inventory_code_id] ||= create_inventory_code
      opts[:pallet_format_id] ||= create_pallet_format
      opts[:cartons_per_pallet_id] ||= create_cartons_per_pallet
      opts[:pm_bom_id] ||= create_pm_bom unless opts.key?(:pm_bom_id)
      opts[:grade_id] ||= create_grade
      opts[:target_market_id] ||= create_target_market unless opts.key?(:target_market_id)
      opts[:pm_mark_id] ||= create_pm_mark unless opts.key?(:pm_mark_id)
      opts[:label_template_id] ||= create_label_template unless opts.key?(:label_template_id)
```

2022-05-03 16:51 UTC, ViljoenFritz commented on lib/messcada/test/factories/carton_factory.rb
> -        tu_sticker_ids: BaseRepo.new.array_for_db_col([]),
done

2022-05-03 16:52 UTC, ViljoenFritz commented on lib/masterfiles/test/factories/standard_product_weight_factory.rb
done

2022-05-04 06:00 UTC, merged