Feature/auto create destination for pallet buildup
NoSoft-SA/nspack pull request #37
Opened 2021-08-12 15:26 UTC by lmatoti

Summary of this change:

Pallet Buildups

Build a pallet by transferring cartons from other pallets

CHANGELOG entry:
Added

Ability to not scan a destination pallet and create it on the fly instead.

Changed

Fixed

.

How to test this code via the UI:
RMD | Buildups | Pallet Buildup

1. New field 'Auto Create Destination Pallet': click it, 'Destination Pallet' is removed from the screen i.e. turns destination pallet on and off
2. Scan source pallets.
3. Scan cartons
4. OnComplete: Destination pallet will be created and scanned cartons moved to it.

2021-08-12 16:54 UTC, jcsjcs requested changes

2021-08-12 16:54 UTC, jcsjcs commented on lib/finished_goods/interactors/buildups_interactor.rb
> +      source = params.select { |k, v| !v.nil_or_empty? && !k.to_s.include?('_scan_field') && !k.to_s.include?('qty_to_move') && !k.to_s.include?('pallet_number') && !k.to_s.include?('auto_create_dest
It seems you want only the values of all params with key `:pnn` (p followed by one or more digits) that are not empty or nil.
This should do it and be future-proof if you add other keys to the params:
```ruby
params.select { |k,v| k.to_s.match(/^p\d+$/) && !v.to_s.empty? }.values.compact
```
Another way would be to get the values for relevant keys, ignoring empty strings and removing nils, like this:
```ruby
params.values_at(*(1..10).map { |n| "p#{n}".to_sym }).grep_v('').compact

# Or break into two so it's easier to read:
pallet_keys = (1..10).map { |n| "p#{n}".to_sym }
params.values_at(*pallet_keys).grep_v('').compact
```
You could also change 10 to 20 so this will work even if the number of pallets is later changed from 10.

2021-08-12 16:54 UTC, jcsjcs commented on lib/finished_goods/interactors/buildups_interactor.rb
> +      pallets = params.select { |k, v| !v.nil_or_empty? && !k.to_s.include?('_scan_field') && !k.to_s.include?('qty_to_move') && !k.to_s.include?('auto_create_destination_pallet') }.values
Same comment as above applies here.

2021-08-12 16:54 UTC, jcsjcs commented on lib/finished_goods/interactors/buildups_interactor.rb
> +      return validation_failed_response(OpenStruct.new(messages: { pallet_number: ['is required'] }))  if params[:auto_create_destination_pallet] == 'f' && params[:pallet_number].nil_or_empty?
You can use a dry validation contract on these parameters that checks that pallet number is needed when auto-create is false. The validation can also exclude the `_scan_fields` for you.

2021-08-12 16:54 UTC, jcsjcs commented on lib/finished_goods/interactors/buildups_interactor.rb
> +            res = MesscadaApp::CreatePalletFromCarton.new(@user, carton_id, 1, nil, false).call
This should work without the default parameters?
```ruby
res = MesscadaApp::CreatePalletFromCarton.new(@user, carton_id, 1).call
```

2021-08-12 16:54 UTC, jcsjcs commented on lib/finished_goods/interactors/buildups_interactor.rb
> +                raise res.message unless res.success
Rather raise a `Crossbeams::InfoError` here.

2021-08-13 12:26 UTC, lmatoti commented
pallet_buildups
changes implemented as per code review

2021-08-13 13:16 UTC, merged