Feature/view mrl results
NoSoft-SA/nspack pull request #370
Opened 2022-05-05 11:49 UTC by WernerVdM97

Summary of this change:
Added a grid showing pass/fail for each mrl chemical result based on mrl chemical requirements.. 

CHANGELOG entry:

### Added
- Menu migration linked to mrl results grid.
- Gemfile changes to support icon columns in grids defined via code.
- Interactor function to calculate pass/fail given mrl requirement id and mrl result id.
- Accompanying repo functions.
### Fixed
- Previous code: qa standards and mrl requirements bugs

2022-05-06 13:06 UTC, jcsjcs requested changes

2022-05-06 13:06 UTC, jcsjcs commented on lib/quality/repositories/mrl_chemicals_requirement_repo.rb
> +    def chemical_ids_and_max_lvls_for(mrl_requirement_id)
Rather use the full word levels instead of lvls.

2022-05-09 14:45 UTC, WernerVdM97 commented on lib/quality/interactors/mrl_result_interactor.rb
> +        cultivar_id, cultivar_name = repo.cultivar_id_and_name_for(mrl_result_id)
This makes a lot of sense yes. Please see this solution https://github.com/NoSoft-SA/nspack/pull/370/commits/0839a70a0aea0d8a189b261daa5444959071b597

2022-05-10 07:04 UTC, jcsjcs requested changes

2022-05-10 07:04 UTC, jcsjcs commented on lib/quality/interactors/mrl_result_interactor.rb
> +          tm_type, tm_id = requirements_repo.target_market_type_and_id_for(column_id)
This query does not need to be performed in the loop. It is being run for every column of every row.

Rather load a hash outside the loop - like: `col_types = { column_id => { tm_type: 'abc', tm_id: 123 } }`
Then inside the loop you just reference the hash: `col_types[column_id][:tm_type]` etc.

2022-05-10 07:05 UTC, jcsjcs commented on lib/quality/interactors/mrl_result_interactor.rb
> +        cultivar_id, cultivar_name = repo.cultivar_id_and_name_for(mrl_result_id)
Yes, that works much better, I have noticed some further optimisations you can do , though - see new comments.

2022-05-10 14:02 UTC, merged