Feature/mrl chemical results
NoSoft-SA/nspack pull request #386
Opened 2022-05-13 11:16 UTC by WernerVdM97

Added a per chemical per target market view showing pass/fail MRL chemical results. Furthermore, upon the addition of a pre harvest chemical to a post harvest MRL result, a duplicate pre harvest MRL result is created/updated containing the same pre harvest chemical value.

### Added
- Routing and view for new chemical results grid.
- Additional columns to capture MRL chemical results.
- Additional columns to MRL results per target market.
- Checks for the addition of a duplicate pre harvest MRL result.
- Repo functions to accomodate the duplication of an MRL result.

2022-05-13 14:43 UTC, jcsjcs requested changes

2022-05-13 14:43 UTC, jcsjcs commented on lib/quality/interactors/mrl_chemicals_result_interactor.rb
> +    rescue Crossbeams::InfoError => e
If there is no code that this method calls that can raise a `Crossbeams::InfoError` then don't rescue it.

2022-05-13 14:43 UTC, jcsjcs commented on lib/quality/interactors/mrl_result_interactor.rb
> +      season_id = repo.get(:mrl_results, :season_id, mrl_result_id)
This can be more efficient (one db query) as:
```ruby
cultivar_id, season_id = repo.get(:mrl_results, %i[cultivar_id season_id], mrl_result_id)
```

2022-05-13 14:43 UTC, jcsjcs commented on lib/quality/interactors/mrl_result_interactor.rb
> +      mrl_requirement_ids_and_tm_names.to_a.each do |mrl_req_id, tm_name|
You don't need the `to_a` here. `Hash.each {|k,v| ...}` will be the same as `Array.each {|k,v| ...}` in this case.

2022-05-16 12:52 UTC, WernerVdM97 commented on lib/quality/interactors/mrl_chemicals_result_interactor.rb
> +      res = calculate_and_validate_mrl_chemicals_result_params(params) unless callback
Stepping through the code I noticed the following:
- Once line 21 performs the callback to `update_or_create_mrl_chemicals_result`, `res` is undefined at first but assigned a new value which is returned from validating `params`. 
- The duplicate chemical result record is then created/updated accordingly.
- However once we step back into line 21 after having created/updated the duplicate record , the value of `res ` is no longer its original value. It has been overwritten by the second instance thereof i.e. that of the duplicate chemical result.
- Therefore the original chemical result is never update/created, but instead the duplicate is update/created twice.

By parsing a duplicate of `res`, such as `to_h` effectively does, does not prevent `res` from being overwritten. Therefore I opted to revalidate `params` as those values are still the original.
Alternatively I considered moving line 21 to 17, before validation overwrites res. This would prevent

2022-05-17 08:40 UTC, WernerVdM97 commented on lib/quality/interactors/mrl_chemicals_result_interactor.rb
> +      res = calculate_and_validate_mrl_chemicals_result_params(params) unless callback
Okay, thanks for the info regarding `to_a` I have now removed the redundant validation in https://github.com/NoSoft-SA/nspack/pull/386/commits/bdb51ad4682ff98a23d2d61ae9fa1798ce9879c9

2022-05-17 08:52 UTC, merged