Feature/multi load
NoSoft-SA/nspack pull request #421
Opened 2022-06-02 08:52 UTC by ViljoenFritz

Summary of this change:

CHANGELOG entry:

### Added
- .
### Changed
- .
### Fixed
- .

How to test this code via the UI:

2022-06-06 12:49 UTC, jcsjcs requested changes

2022-06-06 12:49 UTC, jcsjcs commented on lib/finished_goods/interactors/load_interactor.rb
> +      res
Why did you do this?
Calling code crashes expecting a crossbeams response.

2022-06-08 06:28 UTC, ViljoenFritz commented on lib/finished_goods/interactors/load_interactor.rb
> +      res
TruckArrival.call returns either a validation_failed_response or a success response. 
And there is nothing in the service that would raise a InfoError.

How did the calling code crash

2022-06-08 07:41 UTC, jcsjcs requested changes

2022-06-08 07:41 UTC, jcsjcs commented on lib/finished_goods/interactors/load_interactor.rb
> +      res
I think `check_load!`, `TruckArrival` or something within it raised an InfoError, so res was nil.

2022-06-13 17:58 UTC, ViljoenFritz commented on lib/finished_goods/interactors/load_interactor.rb
> +      res
cool, fixed

2022-06-13 17:58 UTC, ViljoenFritz commented on db/migrations/202205301919_add_multi_load_id_to_loads.rb
> +
fixed

2022-06-13 18:14 UTC, ViljoenFritz commented on lib/finished_goods/test/services/test_truck_arrival.rb
> +
I still have a failing spec here

2022-06-13 18:37 UTC, jcsjcs requested changes

2022-06-13 18:37 UTC, jcsjcs commented on lib/finished_goods/test/services/test_truck_arrival.rb
> +
Then take a look at your code. The following does what you'd expect when injected into an arbitrary test:
```ruby
      AppConst::CR_FG.stub(:verified_gross_mass_required_for_loads?, true) do
        puts 'assert'
        assert AppConst::CR_FG.verified_gross_mass_required_for_loads?
      end
      AppConst::CR_FG.stub(:verified_gross_mass_required_for_loads?, false) do
        puts 'refute'
        refute AppConst::CR_FG.verified_gross_mass_required_for_loads?
      end
```
Is there some other reason why TruckArrival might return a success response?

2022-06-13 19:13 UTC, ViljoenFritz commented on lib/finished_goods/test/services/test_truck_arrival.rb
> +
the setting does not seem to propagate to the schema

2022-06-13 20:37 UTC, jcsjcs requested changes

2022-06-13 20:37 UTC, jcsjcs commented on lib/finished_goods/test/services/test_truck_arrival.rb
> +
OK if you had said `LoadContainerSchema` in the first place I would have seen what you're driving at.

The const is part of the class code, so it is evaluated at load/require time. Change it to a `Contract` and implement the difference in a rule where the state of the constant should be evaluated at runtime, not when loaded.

2022-06-14 07:59 UTC, jcsjcs requested changes

2022-06-14 07:59 UTC, jcsjcs commented on lib/finished_goods/validations/load_container_schema.rb
> +        key.failure('max payload must be provided') if values[:max_payload].nil?
This line should be `key(:max_payload).failure('...')` otherwise it will show as a `tare_weight` failure.

2022-06-17 09:45 UTC, merged