Feature/centralised bin weighing
NoSoft-SA/nspack pull request #426
Opened 2022-06-03 13:52 UTC by lmatoti

Summary of this change:
Bin Weighing
- All bin weights calculations have been centralised into one service

CHANGELOG entry:

### Added
- New service i.e. BinWeighInputs

### Changed
- Updated services UpdateBinWeights and RecalcBinsNettWeight
- Changed all the code that call these two services

How to test this code via the UI:
- Run all apps in the system that (re)calculate bin weights in the system e.g. mescada/reworks apps etc.

2022-06-08 06:21 UTC, jcsjcs requested changes

2022-06-08 06:21 UTC, jcsjcs commented on lib/messcada/services/presort_bin_created.rb
> +                                               provided_nett_weight: representative_bin['Palox_poids'].to_i,
The dry struct will handle converting '123' to 123, so you don't really need the `to_i` part.

2022-06-08 06:21 UTC, jcsjcs commented on lib/production/interactors/production_run_interactor.rb
> +      params[:nett_weight] = res.instance[:nett_weight] if res.success
What if `!res.success`?
You will fail the validation because nett weight has no value, but you will have lost the reason why, so you should return the failed response.

2022-06-08 06:21 UTC, jcsjcs commented on lib/production/jobs/recalculate_bin_nett_weight.rb
> +        rescue Crossbeams::InfoError => e
If you added this just for the InfoErrors in the new service, remove it because the service will not raise info errors.

2022-06-08 06:21 UTC, jcsjcs commented on lib/production/services/recalc_bins_nett_weight.rb
> +          res = MesscadaApp::BinWeigh.call(inputs)
Shouldn't this be used to update something with the weights?

2022-06-08 06:21 UTC, jcsjcs commented on lib/production/services/recalc_bins_nett_weight.rb
> +        raise Crossbeams::InfoError, res.message unless res.success
Why raise an exception? Why not return a failed response?

2022-06-09 13:08 UTC, lmatoti commented on lib/messcada/services/bin_weigh.rb
> +      raise Crossbeams::InfoError, 'container_material_type cannot be empty' unless inputs.rmt_container_material_type_id
Yes, the  DryStruct explodes if you do not provide if you omit rmt_container_material_type_id. However, if rmt_container_material_type_id is provided and it's value is nil, it still needs to be checked

2022-06-14 09:15 UTC, jcsjcs requested changes

2022-06-14 09:15 UTC, jcsjcs commented on lib/production/interactors/reworks_run_interactor.rb
> +      codes['Container Material Owner'] = MasterfilesApp::PartyRepo.new.fn_party_role_name(attrs[:rmt_material_owner_party_role_id]) if attrs.keys.include?(:rmt_material_owner_party_role_id)
Rather add:
```ruby
    def party_repo
      @party_repo ||= MasterfilesApp::PartyRepo.new
    end
```
and use `party_repo`.

2022-06-14 09:15 UTC, jcsjcs commented on lib/production/interactors/reworks_run_interactor.rb
>        codes['Rmt Size'] = @repo.get(:rmt_sizes, :size_code, attrs[:rmt_size_id]) if attrs.keys.include?(:rmt_size_id)
Please change all instances of `@repo` in this file (except in the repo method) to just `repo`.
If no code calls the `repo` method before referring to `@repo`, `@repo` will be nil...

2022-06-17 09:32 UTC, merged