Added:
NoSoft-SA/nspack pull request #430
Opened 2022-06-07 12:08 UTC by WernerVdM97

Summary of this change:
Created a new service which takes in a pallet ID and for each pallet sequence performs an MRL check. The MRL check applies for both pre harvest and post harvest results. The MRL requirement is derived from cultivar plus either a target customer, target market or packed target market group for the pallet sequence. The MRL result (sample) is derived from the farm plus PUC plus season for pre harvest or from the production run for post harvest checks.

CHANGELOG entry:

### Added
- mrl_pallet_check.rb under quality/services
- functions to flatten a QA standard into the encapsulated packed target market groups or target markets.

2022-06-08 10:04 UTC, jcsjcs requested changes

2022-06-08 10:04 UTC, jcsjcs commented on lib/quality/services/mrl_pallet_check.rb
> +      mrl_req = @mrl_req_repo.mrl_requirement_constraints_for(mrl_requirement_id)
You could probably pass the `mrl_req` into this method, instead of passing in the `mrl_requirement_id` and re-reading the table.

2022-06-09 06:14 UTC, jcsjcs requested changes

2022-06-09 06:14 UTC, jcsjcs commented on lib/masterfiles/repositories/qa_standard_repo.rb
> +      id = DB[:qa_standards].where(applies_to_all_markets: true, season_id: season_id, qa_standard_type_id: type_id).get(:id)
As a small optimization, you can create a method that memoizes the type id:
```ruby
def mrl_qa_standard_type_id
  @mrl_qa_standard_type_id ||= get_id(:qa_standard_types, qa_standard_type_code: AppConst::QA_STANDARD_MRL)
end
```
Then instead of querying the db and setting `type_id`, you just call the method `mrl_qa_standard_type_id` wherever you need it in the repo and for the lifetime of the repo instance, the database will be queried only one time to get the value.

2022-06-09 06:14 UTC, jcsjcs commented on lib/quality/services/mrl_pallet_check.rb
> +        # no result equal failure?
You can change this back to "No result equal**s** failure?"

2022-06-09 06:14 UTC, jcsjcs commented on lib/quality/services/mrl_pallet_check.rb
> +      mrl_requirements = []
Rather than storing an array of all `mrl_requirement` objects, just set a boolean:
```ruby
found_nil_requirement - false
@repo.all_hash...
   mrl_requirement = find_mrl_requirement_id_for(pallet_sequence)
  found_nil_requirement = true if mrl_requirement.nil?
  next if mrl_requirement.nil?
  # ...
end
return success_response('Missing MRL requirement(s)') if found_nil_requirement
```
You could instead use a count and return the number of missing requirements (if that would be a useful part of the response to the user)

2022-06-13 07:25 UTC, jcsjcs requested changes

2022-06-13 07:25 UTC, jcsjcs commented on lib/masterfiles/ui_rules/mrl_requirement_rule.rb
> +      return json_actions([]) if params[:changed_value] == ''
Surely you want to replace the select options with `[]` for each of `cultivar_group_id` and `cultivar_id`?
What happens when you test and un-select a season when you already have cultivar + group selected?

2022-06-13 07:25 UTC, jcsjcs commented on lib/masterfiles/ui_rules/mrl_requirement_rule.rb
> +          fields[:season_id][:prompt] = true
Shouldn't cultivar and group options be [] in this case? - to be populated when the season is chosen.
Also: should the season not be set in the `@form_object`?

2022-06-13 09:23 UTC, WernerVdM97 commented on lib/masterfiles/ui_rules/mrl_requirement_rule.rb
> +          fields[:season_id][:prompt] = true
Yes that is better. I have refactored it accordingly.

2022-06-13 09:23 UTC, WernerVdM97 commented on lib/masterfiles/ui_rules/mrl_requirement_rule.rb
> +      return json_actions([]) if params[:changed_value] == ''
Yes I missed this.

2022-06-13 09:32 UTC, jcsjcs requested changes

2022-06-13 09:32 UTC, jcsjcs commented on lib/masterfiles/ui_rules/mrl_requirement_rule.rb
> +      @form_object = OpenStruct.new(season_id: @repo.season_id_of_newest_mrl_requirement,
Use the `merge_hash` option - see http://localhost:9296/developer_documentation/ui_rules.adoc

2022-06-13 09:47 UTC, merged