add validation to govt inspection sheet
NoSoft-SA/nspack pull request #447
Opened 2022-06-15 10:45 UTC by WernerVdM97

As per request from Heila:

On deletion of a govt inspection pallet, if pallet is repacked, a fail validation is returned to prevent the user from deleting the pallet off of the sheet.

### Changed
- `TaskPermissionCheck::GovtInspectionPallet`, function `delete_check`

2022-06-17 06:12 UTC, jcsjcs requested changes

2022-06-17 06:12 UTC, jcsjcs commented on lib/finished_goods/task_permission_checks/govt_inspection_pallet.rb
> +      attr_reader :task, :id, :entity, :args, :repo
There's no need for a reader for `id` - it is never referenced outside the initialize.
In fact the `@id = id` line is redundant.

2022-06-17 06:12 UTC, jcsjcs commented on lib/finished_goods/task_permission_checks/govt_inspection_pallet.rb
> +        return failed_response 'Cant delete Govt Inspection Pallet if pallet has been repacked.' if repo.get(:pallets, :repacked, repo.get(:govt_inspection_pallets, :pallet_id, id))
Please write `Can't` or `Cannot`, but not `Cant`.
Cant: hypocritical and sanctimonious talk, typically of a moral, religious, or political nature.

2022-06-21 07:35 UTC, WernerVdM97 commented on lib/finished_goods/task_permission_checks/govt_inspection_pallet.rb
> +      attr_reader :task, :id, :entity, :args, :repo
I am referencing id on line 62 at the end of the line to get the pallet id.

2022-06-21 11:41 UTC, jcsjcs approved these changes

2022-06-21 11:41 UTC, jcsjcs commented on lib/finished_goods/task_permission_checks/govt_inspection_pallet.rb
> +      attr_reader :task, :id, :entity, :args, :repo
OK. missed that.

2022-06-21 11:41 UTC, merged