Feature/edit truck arrival
NoSoft-SA/nspack pull request #460
Opened 2022-06-28 17:31 UTC by ViljoenFritz

Summary of this change:

CHANGELOG entry:

### Added
- .
### Changed
- .
### Fixed
- .

How to test this code via the UI:

2022-06-29 12:27 UTC, jcsjcs requested changes

2022-06-29 12:27 UTC, jcsjcs commented on lib/finished_goods/interactors/load_truck_arrival_interactor.rb
> +          load_container_id = repo.create_load_container(LoadContainerContract.new.call(params))
Check the contract for `failure?`. Don't just expect it to succeed.

2022-06-29 12:27 UTC, jcsjcs commented on lib/finished_goods/interactors/load_truck_arrival_interactor.rb
> +        load_vehicle_id = repo.create_load_vehicle(LoadVehicleSchema.call(params))
Check the schema for `failure?`. Don't just expect it to succeed.

2022-06-29 12:27 UTC, jcsjcs commented on lib/finished_goods/interactors/load_truck_arrival_interactor.rb
> +          load_container_id = repo.update_load_container(load_container_id, LoadContainerContract.new.call(params))
Check the contract for `failure?`. Don't just expect it to succeed.

2022-06-30 07:35 UTC, ViljoenFritz commented on lib/finished_goods/interactors/load_truck_arrival_interactor.rb
> +        log_status(:load_containers, load_container_id, 'DELETED')
container_id is on load_vehicles, that would raise a PG violation

2022-06-30 07:37 UTC, ViljoenFritz commented on lib/finished_goods/repositories/load_vehicle_repo.rb
> +      load_ids = select_values(:load_vehicles, :id, load_vehicle_id: id)
thanks

2022-06-30 08:03 UTC, jcsjcs commented on lib/finished_goods/interactors/load_truck_arrival_interactor.rb
> +        log_status(:load_containers, load_container_id, 'DELETED')
Oops, working too quickly, not thinking....!

2022-06-30 08:10 UTC, jcsjcs requested changes

2022-06-30 08:10 UTC, jcsjcs commented on lib/finished_goods/interactors/load_truck_arrival_interactor.rb
> +      raise Crossbeams::InfoError, res.message if res.failure?
This will just show "Validation error" as the message if it fails.
Use `failed_message_from_validation` with a `context_message`.

2022-06-30 08:10 UTC, jcsjcs commented on lib/finished_goods/interactors/load_truck_arrival_interactor.rb
> +      raise Crossbeams::InfoError, res.message if res.failure?
This will just show "Validation error" as the message if it fails.
Use `failed_message_from_validation` with a `context_message`.

2022-06-30 17:48 UTC, jcsjcs commented on lib/finished_goods/interactors/load_truck_arrival_interactor.rb
> +      raise Crossbeams::InfoError, res.message if res.failure?
Well you _could_ perhaps use two schemas something like this:
```ruby
v_params = params.slice(*VehicleSchema.key_map.keys.map(&:name))
c_params = params.slice(*ContainerSchema.key_map.keys.map(&:name))
v_res = VehicleSchema.call(v_params)
# ...etc.
```
...but it is pretty ugly, and I'm not sure it's any better.
The ideal would be one contract with a hash for vehicle and a hash for container inside it so you could work with `res[:container]` and `res[:vehicle]` without using 3 schemas.

2022-07-01 11:46 UTC, merged