NO_MERGE | STOCK_ALLOCATION_MODE
NoSoft-SA/nspack pull request #464
Opened 2022-07-04 20:51 UTC by ViljoenFritz

Summary of this change:
Add new column 'stock_allocation_mode' (text) to loads

CHANGELOG entry:

### Added
- .
### Changed
- .
### Fixed
- .

How to test this code via the UI:

2022-07-05 09:26 UTC, jcsjcs requested changes

2022-07-05 09:26 UTC, jcsjcs commented on lib/base_repo.rb
> +  def select_values(table_name, columns, args = {})
This is fine, just modify the yarddoc to explain how args can include `where` or `exclude` hashes.

2022-07-05 13:51 UTC, jcsjcs requested changes

2022-07-05 13:51 UTC, jcsjcs commented on lib/client_rules/client_fg_rules.rb
> +      valid_modes = { standard: 'Stock Pallets',
These should be in AppConst.

2022-07-05 13:51 UTC, jcsjcs commented on lib/client_rules/client_fg_rules.rb
> +      return "Allowed allocation mode hash. #{valid_modes}" if explain
The explanation should only list the modes that are valid for the client.

2022-07-05 13:51 UTC, jcsjcs commented on lib/finished_goods/test/task_permission_checks/test_load.rb
> +        stock_allocation_mode: :standard,
String, not symbol?

2022-07-13 20:47 UTC, ViljoenFritz commented on lib/client_rules/client_fg_rules.rb
> +      valid_modes = { standard: 'Stock Pallets',
Added in table to get the values in the grid

2022-07-28 09:55 UTC, merged