Bin Integration
NoSoft-SA/nspack pull request #49
Opened 2021-08-26 12:17 UTC by lmatoti

Summary of this change:

Bin Integration

Fetches bins from a legacy system and integrates them into the nspack system.

CHANGELOG entry:
Added

1. queue_nspack_bin_integration.rb : This is a script that reads a bins queue table in the legacy system and inserts into a bins queue table in the nspack system.
2. execute_bin_integration_queue.rb : This a script that processes the  bins queue table in the nspack system and creates bin records.

How to test this code:

1. A new bin queue table is created in the legacy system
```sql
-- Table: public.bin_nspack_integration_queue

-- DROP TABLE public.bin_nspack_integration_queue;

CREATE TABLE public.bin_nspack_integration_queue
(
    id integer NOT NULL DEFAULT nextval('bin_nspack_integration_queue_id_seq'::regclass) ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    bin_id integer NOT NULL,
    created_at timestamp without time zone,
    CONSTRAINT bin_nspack_integration_queue_pkey PRIMARY KEY (id),
    CONSTRAINT bins_fk FOREIGN KEY (bin_id)
        REFERENCES public.bins (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.bin_nspack_integration_queue
    OWNER to postgres;
```
2. A trigger that'll populate bin queue table is created in the legacy system is created
```sql
-- DROP TRIGGER create_bin_nspack_integration_queue_entry ON public.bins;
-- DROP FUNCTION public.bin_nspack_integration_queue();

CREATE OR REPLACE FUNCTION bin_nspack_integration_queue()
RETURNS trigger AS
$BODY$
BEGIN
EXECUTE 'INSERT INTO bin_nspack_integration_queue (bin_id, created_at) VALUES($1, now());' USING NEW.id;
    RETURN NEW;
END;
$BODY$
LANGUAGE plpgsql;

CREATE TRIGGER create_bin_nspack_integration_queue_entry
AFTER UPDATE
ON public.bins
FOR EACH ROW
EXECUTE PROCEDURE bin_nspack_integration_queue();
```

3. Run the `queue_nspack_bin_integration.rb` script to read the bins queue table in the legacy system and insert records into a bins queue table in the nspack system.
```bash
RACK_ENV=production ruby scripts/base_script.rb QueueNspackBinIntegration postgres://postgres:postgres@localhost/kromco_local
```
N.B. `postgres://postgres:postgres@localhost/kromco_local` is the url to the legacy database

4. Run the execute_bin_integration_queue.rb script to process the nspack bins queue.
```bash
RACK_ENV=production ruby scripts/base_script.rb ExecuteBinIntegrationQueue
```
This script will read the queue table and start a background job.

5. The background job, once it's run, will create bin records in nspack.

6. UI: `Raw Materials -> Bin Integration Errors -> List`
This lists all the errors per bin if any errors have occurred

7. You can select error bins to schedule them for reprocessing

2021-08-30 13:30 UTC, jcsjcs requested changes

2021-08-30 13:30 UTC, jcsjcs commented on lib/messcada/services/bin_integration.rb
> +      bin_mfs_res = MasterfilesApp::MasterFiles.call({ farm_code: res.instance['farm_code'], orchard_code: res.instance['orchard_code'], product_class_code: res.instance['product_class_code'],
Consider this:
```ruby
fields = %i[farm_code orchard_code] # etc...
hash = Hash[fields.zip(fields.map { |f| res.instance[f.to_s] })]
MasterfilesApp::LookupMasterfiles.call(hash)
```
If `res.instance` has only the keys you need as strings, not symbols, you can just do this:
```ruby
res.instance.to_h.transform_keys(&:to_sym)
```

2021-08-30 13:30 UTC, jcsjcs commented on lib/raw_materials/interactors/bin_integration_queue_interactor.rb
> +    def reprocess_queue(queue)
Rather use `queue_id` here to be more explicit than just `queue`.

2021-08-30 13:30 UTC, jcsjcs commented on lib/raw_materials/interactors/bin_integration_queue_interactor.rb
> +        success_response("legacy bins:#{bins} queued to be reprocessed")
You need to do a `bins.join(', ')` in the message, I think.

2021-08-30 13:30 UTC, jcsjcs commented on lib/raw_materials/repositories/rmt_delivery_repo.rb
> +    def delete_bin_integration_queue(id)
Maybe rename this to `delete_bin_integration_queue_item`.

2021-08-30 13:30 UTC, jcsjcs commented on lib/raw_materials/repositories/rmt_delivery_repo.rb
> +      DB['select max(job_no) from bin_integration_queue'].single_value.to_i + 1
Use a sequence - see https://github.com/NoSoft-SA/nspack/blob/develop/developer_documentation/how_to_work_with_document_sequence_numbers.adoc

2021-08-30 13:30 UTC, jcsjcs commented on lib/raw_materials/jobs/bin_integration_queue_processor_job.rb
> +        RawMaterialsApp::BinIntegrationQueueProcessor.call(job_no)
This must be inside a transaction.

2021-08-30 13:30 UTC, jcsjcs commented on lib/raw_materials/services/bin_integration_queue_processor.rb
> +
This should have:
```ruby
self.maximum_retry_count = 0
```
We do not want this job rerun if it fails. See https://github.com/NoSoft-SA/nspack/blob/develop/developer_documentation/jobs.adoc#non-retry-jobs

2021-08-30 13:30 UTC, jcsjcs commented on scripts/execute_bin_integration_queue.rb
> +      if debug_mode
There is no debug mode.

2021-08-30 13:30 UTC, jcsjcs commented on scripts/queue_nspack_bin_integration.rb
> +    @db_conn[:bin_nspack_integration_queue].distinct.select_map(:bin_id)
You need to get the ids of the `bin_nspack_integration_queue` records too, so that you can delete only the rows that you have read.

2021-08-30 13:30 UTC, jcsjcs commented on scripts/queue_nspack_bin_integration.rb
> +    DB[:bin_integration_queue].where(Sequel.lit("bin_id=#{bin_id} and error IS NOT NULL")).delete
I think you should also delete queue entries that are in error -the new queue entry takes precedence.

2021-08-30 13:30 UTC, jcsjcs commented on scripts/queue_nspack_bin_integration.rb
> +    @db_conn[:bin_nspack_integration_queue].where(bin_id: id).delete
This should only delete the records for this bin that you have actually read from the queue.
To be safe, any later ones should be ignored.

2021-08-30 13:30 UTC, jcsjcs commented on scripts/queue_nspack_bin_integration.rb
> +      if debug_mode
There is no debug mode.

2021-08-31 15:15 UTC, lmatoti commented
Changes made as per code review

2021-08-31 16:19 UTC, jcsjcs commented on scripts/queue_nspack_bin_integration.rb
> +    @db_conn[:bin_nspack_integration_queue].where(id: id).delete
Maybe rename `id` to `ids` here to make it obvious that it is intended to delete a set of records.

2021-09-01 09:50 UTC, lmatoti commented
Changes made as per code review

2021-09-01 14:32 UTC, jcsjcs commented on lib/masterfiles/services/lookup_masterfile_values.rb
>        else
Please create an RMT client rule to replace `AppConst::DELIVERY_USE_DELIVERY_DESTINATION`.
Name it `AppConst::CR_RMT.include_destination_in_delivery?`
It should be true for kr, sr, sr2 and ud, false for all other clients.

2021-09-01 14:55 UTC, lmatoti commented
Changes made as per code review

2021-09-01 15:01 UTC, jcsjcs commented on lib/masterfiles/services/lookup_masterfile_values.rb
>        else
Thank you, but you have not entirely replaced the client setting with the client rule.
Please update the following files too:
```
lib/raw_materials/ui_rules/rmt_delivery_rule.rb
lib/messcada/services/bin_integration.rb
config/client_settings_loader.rb
```

2021-09-01 16:58 UTC, lmatoti commented
Changes made as per code review

2021-09-01 17:47 UTC, merged