Feature/stock allocation mode
NoSoft-SA/nspack pull request #512
Opened 2022-08-05 11:35 UTC by FritzViljoen

CHANGELOG entry:

Added
Stock allocation modes to loads
How to test this code via the UI:

pallet allocation behaviours
For all modes below: shipping and truck arrival needs to apply same checks/rules, except for the pre-stock and failed_stock modes

stock(standard): pallets can only be allocated or shipped if in stock (pallet.stock is true)
pre_stock: pallets can be allocated regardless of stock state or inspected state, but not when inspected and
inspection failed
shipping/truck arrival: at this point pallets must be in stock (inspected state does not matter)
failed_stock: pallets can be allocated regardless of stock state or inspected state or inspection results
shipping/truck arrival: pallets must be inspected, but results does not matter
uninspected_stock: pallets can be allocated regardless of inspected or stock state; same applies to shipping
rmt bins: pallets can be allocated regardless of stock or inspected state or results, but pallets must have a rmt grade
and bin pack-type; same applies to shipping

2022-08-11 08:47 UTC, jcsjcs requested changes
Please note there is a merge conflict on this PR.

2022-08-11 08:47 UTC, jcsjcs commented on lib/finished_goods/repositories/load_repo.rb
> +      when :standard
Use a const here.

2022-08-11 08:47 UTC, jcsjcs commented on lib/finished_goods/task_permission_checks/load.rb
> +        checks -= if AppConst::CR_FG.load_stock_allocation_modes.include? :pre_stock
Surely this should depend on the actual mode of the load, not just that it is possible to choose this mode? Or does pre-load mean that this is before there is a load - in which case when is this check used?

2022-08-11 08:47 UTC, jcsjcs commented on lib/finished_goods/task_permission_checks/load.rb
> +        when :standard
Use consts.

2022-08-11 08:47 UTC, jcsjcs commented on lib/finished_goods/task_permission_checks/load.rb
> +        when :standard
Consts.

2022-08-16 18:02 UTC, FritzViljoen commented on lib/finished_goods/task_permission_checks/load.rb
> +        checks -= if AppConst::CR_FG.load_stock_allocation_modes.include? :pre_stock
it is only used in nsli_in.rb

2022-08-16 18:25 UTC, FritzViljoen commented on lib/client_rules/client_fg_rules.rb
> +            load_stock_allocation_modes: %i[standard] },
App_Const is not accessible from within the CLIENT_SETTINGS hash

2022-08-18 07:10 UTC, merged