feature/container_code_pattern
NoSoft-SA/nspack pull request #517
Opened 2022-08-11 19:07 UTC by FritzViljoen

CHANGELOG entry:
load container_code for client UD must now conform to pattern 'abc1234567'

### Added
- regex test to truck arrival contract

How to test this code via the UI:
on load do a truck arrival and update a container code

2022-08-12 06:22 UTC, jcsjcs requested changes

2022-08-12 06:22 UTC, jcsjcs commented on lib/finished_goods/validations/load_truck_arrival_contract.rb
> +      optional(:container_code).maybe(Types::StrippedString, format?: AppConst::CR_FG.load_container_code_regex)
If you implement the format check as a rule, you'll be able to test with different client codes.

Note: you should probably also use the `:pattern` attribute of the renderer to get the browser to do the check in the form itself. Quicker response to the user and better UX.

2022-08-12 13:59 UTC, jcsjcs requested changes

2022-08-12 13:59 UTC, jcsjcs commented on lib/client_rules/client_fg_rules.rb
> +            load_container_code_regex: /^[a-zA-Z]{3}\d{7}$/,
The regex requirement was incorrectly stated. Please change to 4 characters and 7 digits.

2022-08-15 18:58 UTC, FritzViljoen commented on lib/client_rules/client_fg_rules.rb
> +            load_container_code_regex: /^[a-zA-Z]{3}\d{7}$/,
changed to /^[a-zA-Z]{4}\d{7}$/ for UD

2022-08-15 18:59 UTC, FritzViljoen commented on lib/finished_goods/validations/load_truck_arrival_contract.rb
> +      optional(:container_code).maybe(Types::StrippedString, format?: AppConst::CR_FG.load_container_code_regex)
cool idea, I implemented the rule change

2022-08-16 12:21 UTC, merged