Phyto Reports
NoSoft-SA/nspack pull request #519
Opened 2022-08-15 13:13 UTC by lmatoti

Phyto Reports

Summary of this change:
Added ability for the system to 'remember' phyto_pallet selection i.e. save the selection to db tables.

CHANGELOG entry:

### Added
- phyto_report & phyto_report_pallets tables

How to test this code via the UI:
Finished Goods | Inspection | Phyto Reports
1. Create phyto_report: select pack_tm_group and/or target_market. Then select (stock) pallets to add to the report.
2. View phyto_report
3. Manage Stock Pallets: See a stock_pallets grid with pallets to belong to this phy_to_report already selected. De-select those you want to remove and select those you want to remove.
4. Manage Shipped Pallets: See a shipped_pallets grid with add and remove button on top. User will only be able to see this grid if they have the permission(can_change_inspected_pallets).
5. Delete phyto_report: User will only be able to delete report if they have the permission(can_change_inspected_pallets).

2022-08-16 14:00 UTC, jcsjcs requested changes

2022-08-16 14:00 UTC, jcsjcs commented on lib/finished_goods/interactors/inspection_interactor.rb
> +        log_status(:phyto_reports, phyto_report_id, "SHIPPED_PALLETS_ADDED:#{pallets.map { |p| p[:pallet_number] }.join(',')}")
Split the status - `'SHIPPED_PALLETS_ADDED', comment: pallets.map { |p| p[:pallet_number] }.join(',')}`

2022-08-16 14:00 UTC, jcsjcs commented on lib/finished_goods/interactors/inspection_interactor.rb
> +        end
Perhaps you can create a repo method like this:
```ruby
def add_pallets_to_phyto_report(phyto_report_id, pallet_ids)
  DB[:phyto_report_pallets].multi_insert(pallet_ids.map { |id| {phyto_report_id: phyto_report_id, pallet_id: id } })
end
```
Then you can add all pallets at once: `repo.add_pallets_to_phyto_report(id, pallet_ids)` and you can use the same repo method below in `add_shipped_pallets`.

2022-08-16 14:00 UTC, jcsjcs commented on lib/finished_goods/interactors/inspection_interactor.rb
> +        pallets = dataminer_report_rows(rpt)
Isn't `pallets` just the same as `new_shipped_report_pallets`?

2022-08-16 14:00 UTC, jcsjcs commented on lib/finished_goods/interactors/inspection_interactor.rb
> +        log_status(:phyto_reports, id, "SHIPPED_PALLETS_REMOVED:#{pallet_numbers.join(',')}")
Again, split the status into status and comment.

2022-08-16 14:00 UTC, jcsjcs commented on lib/finished_goods/interactors/inspection_interactor.rb
> +          repo.create_phyto_report_pallet(phyto_report_id: phyto_report_id, pallet_id: new_pallet_id)
Use the new repo method here to add all pallets at once.

2022-08-16 14:00 UTC, jcsjcs commented on lib/finished_goods/interactors/inspection_interactor.rb
> +        log_status(:phyto_reports, phyto_report_id, "EDITED: #{added_status} #{deleted_status}")
Split status into status and comment.

2022-08-16 14:00 UTC, jcsjcs commented on routes/finished_goods/reports.rb
> +      pallet_ids = report_repo.select_values(:phyto_report_pallets, :pallet_id, phyto_report_id: id)
Move these two lines into a method in the interactor.

2022-08-17 08:50 UTC, lmatoti commented on lib/finished_goods/interactors/inspection_interactor.rb
> +        pallets = dataminer_report_rows(rpt)
new_shipped_report_pallets is a list of pallet_numbers
pallets is a list of pallet records used to update the grid

2022-08-17 09:07 UTC, jcsjcs commented on lib/finished_goods/interactors/inspection_interactor.rb
> +        pallets = dataminer_report_rows(rpt)
OK, I see you use the report output in your `success_response`. You can still use `new_shipped_report_pallets` in the `log_status` call, though.

2022-08-17 16:15 UTC, merged