Feature/titan refactor
NoSoft-SA/nspack pull request #534
Opened 2022-08-30 07:30 UTC by WernerVdM97

Summary of this change:
Refactored TITAN integration for inspecting govt inspection sheets. The state of a TITAN inspection is now stored in the database table titan_inspections, allowing for better control over which requests the user is allowed to call via the API.

CHANGELOG entry:
### Added

- Table `titan_inspections` to save the state of an titan inspection. Including:
  - Schema, routing, entity, interactor, repo, task permission check and barebone tests (to be expanded via mock API).
-  Added relevant information to `titan_inspection` view and UI rule:
  - Focus message containing most recent applicable warning/notice for TITAN inspection
  - eCert tracking grid for applicable pallets
  - Progress bar to visualise inspection status.
- All possible states and API modes to `appconst`.
- Tracking unit status to eCert tracking units grid action menu
- Functions to change the titan inspection state for both un- and succussful eCert preverification in `ecert_tracking_unit_interactor`.
- Routing for eCert preverification and tracking unit status via popup from titan_inspection view.

### Changed
- Changed service filename from `TitanInspection` to `TitanInspectionService` and:
  - automatically decide between `validate` and `validate by consignment` upon requesting validation.
  - added `titan_state_rec` hash to change state of titan inspection depending on API results.
- Govt Inspection sheets grid to better portray TITAN status.
- eCert tracking units grid SQL allowing for filter by govt inspection sheet.
- eCert tracking unit status UI rule and view to handle being loaded as popup via action menu

### Fixed
- TITAN requests view properly shows entire API request JSON in `titan_repo`.

### Removed
- Unused column `awaiting_inspection_results` from `govt_inspection_sheets`.
- Irrelevant columns from eCert tracking units Diff in `ecert_repo`.

How to test this code via the UI:
| Finished Goods | Inspection | Govt Inspection Sheets | menu (Action Menu) | Titan Inspection ...

2022-08-30 13:45 UTC, jcsjcs requested changes

2022-08-30 13:45 UTC, jcsjcs commented on lib/finished_goods/repositories/titan_repo.rb
>      end
Perhaps simplify this method and apply a similar pattern to: 
* `parse_titan_inspection_result_doc`
* `parse_titan_addendum_request_doc`
* `parse_titan_addendum_result_doc`.
```ruby
def parse_titan_inspection_request_doc(hash)
  return hash.merge(request_array: []) unless hash[:request_doc]

  hash[:request_array] = flatten_to_table(hash[:request_doc].except('consignmentLines'))
  hash[:request_array] += flatten_to_table(hash[:request_doc]['consignmentLines'] || [])
  hash
end

2022-08-30 13:45 UTC, jcsjcs commented on lib/finished_goods/ui_rules/titan_inspection_rule.rb
> +
You can farm out these rules to a `TaskPermissionCheck` - something like:
```ruby
tpm = TitanStatusTaskPermissionCheck.new(@form_object[:titan_action_status]), @form_object[:validation_passed])

preverify[:visible] = tpm.call(:can_preverify)
inspect[:visible] = tpm.call(:can_inspect)
#...etc.
```

2022-08-30 13:45 UTC, jcsjcs commented on lib/finished_goods/views/ecert_tracking_unit/loading.rb
> +          layout = Crossbeams::Layout::Page.build({}) do |page|
Remove the `layout =`

2022-08-31 14:56 UTC, WernerVdM97 commented on lib/finished_goods/interactors/ecert_tracking_unit_interactor.rb
> +
See 
https://github.com/NoSoft-SA/nspack/pull/534/commits/3672639a7f109e831002eb47413cbde70fdc9b3d

2022-08-31 14:56 UTC, WernerVdM97 commented on lib/finished_goods/repositories/titan_repo.rb
>      end
See 
https://github.com/NoSoft-SA/nspack/pull/534/commits/72924a1486186b17c9b5d3ee9805aa1874eda7d1

2022-08-31 14:57 UTC, WernerVdM97 commented on lib/finished_goods/ui_rules/titan_inspection_rule.rb
> +
See 
https://github.com/NoSoft-SA/nspack/pull/534/commits/5e013b71985f5f7e30c98dbb26fc637ce1936e4e

2022-09-01 05:36 UTC, jcsjcs commented on lib/finished_goods/repositories/titan_repo.rb
>      end
Looks good.

2022-09-01 05:41 UTC, jcsjcs commented on lib/finished_goods/ui_rules/titan_inspection_rule.rb
> +
I meant you to leave the existing permission check for the titan inspection as is and add a new task permission check just for the titan statuses.

2022-09-01 05:46 UTC, jcsjcs commented on lib/finished_goods/interactors/ecert_tracking_unit_interactor.rb
> +
Looks good, I would just make `validate_ecert_preverification_params` private.

2022-09-01 08:06 UTC, WernerVdM97 commented on lib/finished_goods/interactors/ecert_tracking_unit_interactor.rb
> +
I left it public as I am currently calling it from routes/finished_goods/inspection.rb L:197

```ruby

r.on 'preverify_popup', Integer do |titan_inspection_id|
  check_auth!('inspection', 'edit')
  ecert_interactor = FinishedGoodsApp::EcertTrackingUnitInteractor.new(current_user, {}, { route_url: request.path, request_ip: request.ip }, {})
  res = ecert_interactor.validate_ecert_preverification_params(params.merge(titan_inspection_id: titan_inspection_id, govt_inspection_sheet_id: id))
  raise Crossbeams::FrameworkError, res.message unless res.success?

  params = { govt_inspection_sheet_id: res[:govt_inspection_sheet_id],
             remote: fetch?(r),
             popup: true,
             titan_inspection_id: res[:titan_inspection_id],
             call_titan_update: res[:call_titan_update],
             reinspection: res[:reinspection] }
  show_partial_or_page(r) { FinishedGoods::Ecert::EcertTrackingUnit::New.call(params) }
end
```
I could drop this as it can be expected that each of the parameters are valid, given they are not user generated but originate from the code itself. Initially, I put this in as a precaution but dropping it would allow me to make `validate_ecert_preverification_params` private.

2022-09-01 08:09 UTC, WernerVdM97 commented on lib/finished_goods/ui_rules/titan_inspection_rule.rb
> +
See https://github.com/NoSoft-SA/nspack/pull/534/commits/dd35fe976c0cfbd9538d20afdbd0d19bc668a668

2022-09-01 08:44 UTC, merged