Feature/inspection sheet tm mixing
NoSoft-SA/nspack pull request #587
Opened 2022-10-24 14:02 UTC by WernerVdM97

# Summary of this change:
Allow multiple target markets to be specified on a government inspection sheet. For each pallet, the destination region/country eCert agreement and titan protocol exception can be set via an inline editing grid on the govt inspection sheet view.

## CHANGELOG entry:

### Added
- Client rule to allow target market mixing on govt inspection sheets. Only true for Kromco.
- Mock eCert API functionality to preverify pallets.
- To `govt inspection pallets`: 
  - Foreign keys specifying the destination region, -country and eCert agreement.
  - Titan protocol exception.
  - Booleans indicating manually inspected and timestamp.
- Grid definitions for an inline editable govt inspection pallets grid with the applicable fields above.
  - features a bulk update titan protocol button.
- Boolean `allow_tm_mixing` to `govt inspection sheets`, upon selection, destination region, -country, titan protocol exception and packed tm group become null.
- Commodity and country array columns to eCert agreements which are populated upon calling `get eCert agreements`.
- Repo function to filter the applicable destination region, -countries and eCert agreements for a pallet.

### Changed
- Moved the Titan protocol exceptions from AppConst to a database table.
- EDI repo functions to derive destination region/country from govt inspection pallets.
- Changed govt inspection pallets UI rules and views to support:
  - bulk update titan protocol and
  - set destination region, -country and eCert agreement.
- Titan Inspection UI rules to not produce eCert preverify popup for mixed tm govt inspection sheets. It is now required for all pallets to be preverified before creating a titan inspection for govt inspection sheets with mixed TMs.

## How to test this code via the UI:
### | Finished Goods | Inspections | Create a new inspection with Allow TM mixing = True. 
- Requires that the client rule `allow_tm_mixing_on_inspection_sheets` be true as well as the Applicable eCert credentials be set in the respective .env file.
- Destination countries, -regions, ecert agreements and titan exception protocols can be tested via the `set destination regions` button on the govt inspection sheet view.
- Both mixed and non-mixed TM eCert pre-verification and thereafter Titan Inspection must be tested.
- The EDI columns in PO, PI and A1-PO: destination region/country must be tested for mixed TMs.
- Getting the latest set of eCert agreements to update the commodity and country arrays.
- Adding non- and manually inspected pallets to govt inspection sheets.

2022-10-25 10:36 UTC, jcsjcs requested changes

2022-10-25 10:36 UTC, jcsjcs commented on lib/finished_goods/services/ecert_preverify.rb
> +          end
To avoid the loop and several queries:
```ruby
ids = repo.select_values(:pallets, :id, pallet_number: create_units)
unit_ids = repo.select_values(:ecert_tracking_units, :id, pallet_id: ids)
repo.update(:ecert_tracking_units, unit_ids, passed: false)
```

2022-10-25 10:36 UTC, jcsjcs commented on lib/masterfiles/repositories/destination_repo.rb
> +      DB[:destination_regions].where(destination_region_name: name).get(:id)
```ruby
get_id(:destination_regions, destination_region_name: name)
```

2022-10-25 10:36 UTC, jcsjcs commented on lib/masterfiles/repositories/destination_repo.rb
> +    end
```ruby
get_id(:destination_countries, country_name: name)
```

2022-11-01 15:10 UTC, closed without merging

2022-11-01 15:10 UTC, WernerVdM97 commented
Rebase failed. Opening new pull request.