MRL bugfixes
NoSoft-SA/nspack pull request #705
Opened 2023-02-20 10:12 UTC by WernerVdM97

Summary of this change:
- Fixed erroneous update of pre-harvest child result where `pre_harvest_id IS nil` (Applicable to clients with `capture_mrl_result_per_chemicial = false`.
- Rename date time (..._at) fields to date (..._date) fields:
  - fruit_received_at
  - result_received_at
  - sample_submitted_at

2023-02-20 13:14 UTC, jcsjcs requested changes

2023-02-20 13:14 UTC, jcsjcs commented on db/migrations/202302201000_rename_mrl_results_columns_from_at_to_date.rb
> +    alter_table(:mrl_results) do
These should also be changed to date types.
Try
```ruby
set_column_type :fruit_received_at, Date
```
Or
```sql
ALTER TABLE public.mrl_results ALTER COLUMN fruit_received_at TYPE date USING fruit_received_at::date;
```

2023-02-20 13:14 UTC, jcsjcs commented on lib/quality/interactors/mrl_result_interactor.rb
> +                                           sample_submitted_date: Time.now,
`Date.today`

2023-02-20 13:14 UTC, jcsjcs commented on lib/quality/test/factories/mrl_result_factory.rb
> +        result_received_date: '2010-01-01 12:00',
Remove the time portions from these strings.

2023-02-20 13:14 UTC, jcsjcs commented on lib/quality/test/interactors/test_mrl_result_interactor.rb
> +        result_received_date: '2010-01-01 12:00',
Remove the time portions from these strings.

2023-02-20 13:14 UTC, jcsjcs commented on lib/quality/test/task_permission_checks/test_mrl_result.rb
>          active: true,
Remove the time portions from these strings.

2023-02-20 13:14 UTC, jcsjcs commented on lib/quality/ui_rules/mrl_result_rule.rb
> +      fields[:result_received_date] = { renderer: :label, with_value: @form_object.result_received_date.strftime('%Y-%m-%d') }
The `with_value` should not be required when the columns are no longer `Time`s.

2023-02-20 13:14 UTC, jcsjcs commented on lib/quality/ui_rules/mrl_result_rule.rb
> +                               maxvalue: Time.now.strftime('%Y-%m-%d'),
`Date.today` for this and the others.

2023-02-20 13:14 UTC, jcsjcs commented on lib/quality/ui_rules/mrl_result_rule.rb
> +      hash = @form_object.map.to_h { |k, v| %i[fruit_received_date sample_submitted_date result_received_date].include?(k) ? [k, v.strftime('%Y-%m-%d')] : [k, v] }
Should not be required when you change the column type to `Date`.

2023-02-20 13:14 UTC, jcsjcs commented on lib/quality/ui_rules/mrl_result_rule.rb
> +                                                               fruit_received_date: Time.now,
`Date.today`.

2023-02-20 13:14 UTC, jcsjcs commented on lib/quality/validations/mrl_result_schema.rb
> +    required(:fruit_received_date).filled(:time)
`filled(:date)` for all these fields.

2023-02-20 14:55 UTC, jcsjcs requested changes

2023-02-20 14:55 UTC, jcsjcs commented on lib/quality/ui_rules/mrl_result_rule.rb
> +                                                               fruit_received_date: Time.now,
Still Time...

2023-02-21 07:20 UTC, WernerVdM97 commented on lib/quality/ui_rules/mrl_result_rule.rb
> +                                                               fruit_received_date: Time.now,
Apologies, I have been too rushed with this. I fixed it now and double-checked the interactor as well.

2023-02-21 08:34 UTC, merged