Feature/pdt depot receipts
NoSoft-SA/nspack pull request #765
Opened 2023-05-09 12:53 UTC by lmatoti

Summary of this change:
Pdt Depot Receipts
This application validates depot receipts that were received (preceded) via edi. The user checks the correctness of the edi information for each pallet by physically comparing the edi pallet info with pallet (and carton) label info.

CHANGELOG entry:

### Added
- New rmd depot receipts application

How to test this code via the UI:
RMD | Depot Receipts |  Manually Validate
Enter Document Number
- The user scans a 'Edi In Load Number' i.e. the PO OH record's load_ref.The latest/newest PO is looked up and validated.

Validate Pallet Qty
- User scans 'Pallets Qty'. The system validates the entered qty (physical quantity of pallets on the truck) vs the edi doc’s pallet count. If different, the user is asked if they want to override the PO's pallet qty.

PO has missing mfs
- The system shows the user the missing mf screen if there are any missing mfs.

Per Pallet Validations And Data Changes
- User scans a pallet_number. System validates it.
- The system displays the pallet and sequence info on a single screen in edit mode.
- If there's only one value for a certain field for all the sequences, only one text_box will be displayed.
- If there's more than one value for a certain field for the sequences, more text_boxes will be displayed for each group of sequences
- Once the user is satisfied with the pallet info or has edited/corrected relevant fields, they need to choose valid/invalid from the valid? dropdown to indicate if the pallet info is correct or not N.B. The process can only be completed once all pallets have been marked as 'valid'.
- The system presents the user with the 'Scan Pallet' screen. Once the user has validated/invalidated all the pallets the user can click the 'complete' button to complete the process.
- If there are pallet that have not been validated and/or there are pallets that have been 'invalidated' by the user, the system will notify the user of these.

2023-05-19 13:39 UTC, jcsjcs requested changes

2023-05-19 13:39 UTC, jcsjcs commented on routes/rmd/edi.rb
> +                         scan: 'key248_all',
Surely these should not be scan fields?

2023-05-19 13:39 UTC, jcsjcs commented on routes/rmd/edi.rb
> +                         scan: 'key248_all',
Is this supposed to be scanned?

2023-05-19 13:39 UTC, jcsjcs commented on lib/edi/interactors/depot_receipts_interactor.rb
> +      return failed_response("PO Document:#{edi_in_load_number} contains pallet that already exist in the system.") unless existing_pallets.size.zero?
Include the 1st pallet number in this message.

2023-05-19 13:39 UTC, jcsjcs commented on lib/edi/interactors/depot_receipts_interactor.rb
> +      seq_1 = record_set.select { |rec| rec['record_type'].to_s == 'OP' && rec['sscc'] == pallet_number && rec['seq_no'].to_i == 1 }[0]
Use `find` to get the first match instead of `select { }[0]`

2023-05-19 13:39 UTC, jcsjcs commented on lib/edi/interactors/depot_receipts_interactor.rb
> +      date_time_format_fields = EdiApp::FlatFileRepo.new('po').record_definitions['OP'].map { |_, v| v }.find_all { |f| (f.format == 'DATE' || f.format == 'DATETIME') && submitted_form_fields.include
`.map { |_, v| v }` is the same as `.values`

2023-05-22 07:46 UTC, lmatoti commented on routes/rmd/edi.rb
> +                         scan: 'key248_all',
Yes. This is a barcode on a printed document

2023-05-22 08:26 UTC, merged